/**
 * ChannelEntityPanel displays a channel's named-entity ranking (Feature 070).
 *
 * Read-only ranking display (US1): the share-ranked group (server-ordered by
 * distinctiveness) followed by an "also appears" group of entities that show
 * up in exactly one of the channel's videos.
 *
 * Pin-to-filter (US2): each row also renders a pin toggle. Pinning composes
 * one or more entities into an AND-intersection filter for the channel's
 * video list (`ChannelDetailPage`), encoded as repeated `entity_id` URL
 * params via `usePinnedEntities` so the filter is shareable and reload-safe
 * (FR-006 / SC-004). "Show all" / top-10 truncation remains a later story —
 * the row-level structure (`EntityRankingRow`) stayed separate for exactly
 * this reason.
 *
 * Accessibility (FR-015):
 * - A visible `<h2>` heading names the panel.
 * - Both groups render as semantic lists (`role="list"` / `role="listitem"`).
 * - A `role="status"` / `aria-live="polite"` region announces the loaded
 *   count once data resolves, without duplicating the visible heading.
 * - Each pin control is a real toggle button (`aria-pressed`, keyboard
 *   operable, visible focus ring) and a separate `aria-live="polite"` region
 *   announces pin/unpin changes.
 */

import { useCallback, useState } from "react";

import { useChannelEntities } from "../../hooks/useChannelEntities";
import { usePinnedEntities } from "../../hooks/usePinnedEntities";
import { EntityName } from "../EntityName";
import { colorTokens, cardPatterns } from "../../styles";
import type { ChannelEntityRanking } from "../../types/channel";

export interface ChannelEntityPanelProps {
  /** YouTube channel ID whose entity ranking should be displayed. */
  channelId: string;
}

/**
 * Entities shown before the panel offers a "Show all N" control (FR-009). The
 * endpoint returns the full ranked list; this top-N is a client-side
 * presentation concern, view-local (not URL-persisted) and re-collapsible.
 */
const TOP_N = 10;

/**
 * Formats a distinctiveness share (a float in (0, 1]) as a whole-number
 * percentage string, per FR-011.
 *
 * FR-011: shares **below 1%** display as "<1%"; all others are rounded to the
 * nearest whole percent. The threshold is the raw share (< 1%), NOT the rounded
 * value — a 0.7% share is below 1% and must read "<1%", never round up to "1%"
 * and overstate a tiny share.
 *
 * Guards against a non-finite share (the API response is not runtime-validated,
 * so a future backend regression shipping ``null`` would otherwise render the
 * literal string "NaN%").
 */
function formatSharePercent(share: number): string {
  if (!Number.isFinite(share)) {
    return "—";
  }
  const percent = share * 100;
  if (percent < 1) {
    return "<1%";
  }
  return `${Math.round(percent)}%`;
}

interface PinToggleButtonProps {
  displayName: string;
  isPinned: boolean;
  onToggle: () => void;
}

/**
 * Pin/unpin toggle for one entity row (US2, FR-015).
 *
 * Uses only literal Tailwind classes — a `bg-${token}` string is never
 * generated by the JIT compiler and would ship an unstyled control.
 */
function PinToggleButton({ displayName, isPinned, onToggle }: PinToggleButtonProps) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-pressed={isPinned}
      aria-label={isPinned ? `Unpin ${displayName}` : `Pin ${displayName} to filter`}
      title={isPinned ? "Unpin" : "Pin to filter"}
      className={
        isPinned
          ? "inline-flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full border border-blue-600 bg-blue-600 text-white transition-colors hover:bg-blue-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-1"
          : "inline-flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full border border-gray-300 bg-white text-gray-500 transition-colors hover:bg-gray-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-1"
      }
    >
      <svg
        className="h-3.5 w-3.5"
        fill={isPinned ? "currentColor" : "none"}
        stroke="currentColor"
        strokeWidth={1.75}
        viewBox="0 0 24 24"
        aria-hidden="true"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M9.75 3.104v5.714a2.25 2.25 0 0 1-.659 1.591L5 14.5V16h14v-1.5l-4.091-4.091a2.25 2.25 0 0 1-.659-1.591V3.104M12 16v5"
        />
      </svg>
    </button>
  );
}

interface EntityRankingRowProps {
  entity: ChannelEntityRanking;
  isPinned: boolean;
  onTogglePin: (entity: ChannelEntityRanking) => void;
}

function EntityRankingRow({ entity, isPinned, onTogglePin }: EntityRankingRowProps) {
  const percentLabel = formatSharePercent(entity.share);
  const videoLabel = `${entity.channel_video_count} video${entity.channel_video_count === 1 ? "" : "s"}`;

  return (
    <li
      role="listitem"
      className={`flex flex-wrap items-center justify-between gap-3 py-3 border-b border-${colorTokens.border} last:border-b-0`}
    >
      <div className="flex items-center gap-2 min-w-0">
        <PinToggleButton
          displayName={entity.display_name}
          isPinned={isPinned}
          onToggle={() => onTogglePin(entity)}
        />
        <EntityName name={entity.display_name} entityType={entity.entity_type} />
      </div>
      <div className="flex items-center gap-4 text-sm">
        <span className={`text-${colorTokens.text.secondary}`}>{videoLabel}</span>
        <span
          className={`font-semibold text-${colorTokens.text.primary}`}
          aria-label={`${percentLabel} distinctiveness share`}
        >
          {percentLabel}
        </span>
      </div>
    </li>
  );
}

/**
 * Skeleton row for the loading state, matching `EntityRankingRow`'s layout.
 */
function SkeletonRow() {
  return (
    <li className="flex items-center justify-between gap-3 py-3 animate-pulse" aria-hidden="true">
      <div className="flex items-center gap-2">
        <div className="h-6 bg-gray-200 rounded-full w-32" />
        <div className="h-6 bg-gray-200 rounded-full w-20" />
      </div>
      <div className="flex items-center gap-4">
        <div className="h-4 bg-gray-200 rounded-md w-16" />
        <div className="h-4 bg-gray-200 rounded-md w-10" />
      </div>
    </li>
  );
}

export function ChannelEntityPanel({ channelId }: ChannelEntityPanelProps) {
  const { data, isLoading, isError, error, refetch } = useChannelEntities(channelId);
  const { isPinned, togglePin } = usePinnedEntities();

  // FR-015: a pin/unpin toggle is announced separately from the loaded-count
  // region above, so the two announcements never overwrite one another.
  const [pinAnnouncement, setPinAnnouncement] = useState("");

  // FR-009: large channels render the top 10 by distinctiveness with a single
  // "Show all N" control. View-local, re-collapsible, not URL-persisted.
  const [expanded, setExpanded] = useState(false);

  const handleTogglePin = useCallback(
    (entity: ChannelEntityRanking) => {
      const wasPinned = isPinned(entity.entity_id);
      togglePin(entity.entity_id);
      setPinAnnouncement(
        wasPinned
          ? `Unpinned ${entity.display_name}`
          : `Pinned ${entity.display_name} to filter`
      );
    },
    [isPinned, togglePin]
  );

  return (
    <section className={`${cardPatterns.base} p-6 mb-8`} aria-labelledby="channel-entities-heading">
      <h2
        id="channel-entities-heading"
        className={`text-2xl font-bold text-${colorTokens.text.primary} mb-4`}
      >
        Entities
      </h2>

      {/* No role="status": the loading/loaded-count regions below already use
          that role, and this announcement is live regardless of the loading
          state — a second role="status" would make getByRole("status")
          ambiguous. aria-live alone is enough for it to be announced. */}
      <div aria-live="polite" aria-atomic="true" className="sr-only">
        {pinAnnouncement}
      </div>

      {isLoading && (
        <div role="status" aria-busy="true">
          <ul aria-hidden="true" className="divide-y divide-transparent">
            <SkeletonRow />
            <SkeletonRow />
            <SkeletonRow />
          </ul>
          <span className="sr-only">Loading entities…</span>
        </div>
      )}

      {!isLoading && isError && (
        <div
          className={`bg-${colorTokens.status.error.bg} border border-${colorTokens.status.error.border} rounded-lg p-6 text-center`}
          role="alert"
        >
          <p className={`text-${colorTokens.status.error.text} font-medium mb-4`}>
            Could not load entities:{" "}
            {error?.message ?? "An error occurred"}
          </p>
          <button
            type="button"
            onClick={refetch}
            className="inline-flex items-center px-4 py-2 bg-red-600 text-white font-medium rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 transition-colors"
          >
            Retry
          </button>
        </div>
      )}

      {/* Branch on the actual items rendered, not total_entities, so a
          (contract-impossible) count/items mismatch can never leave a silently
          blank panel under a "Loaded N entities" announcement. */}
      {!isLoading && !isError && data && data.items.length === 0 && (
        <p role="status" className={`text-${colorTokens.text.secondary}`}>
          No entities found for this channel yet.
        </p>
      )}

      {!isLoading && !isError && data && data.items.length > 0 && (
        <>
          <div role="status" aria-live="polite" className="sr-only">
            {`Loaded ${data.items.length} entit${data.items.length === 1 ? "y" : "ies"}`}
          </div>

          {(() => {
            const ranked = data.items.filter((item) => item.is_ranked);
            const alsoAppears = data.items.filter((item) => !item.is_ranked);
            const total = data.items.length;
            // Collapsed: top-10 ranked only, "also appears" hidden (FR-009).
            const collapsed = total > TOP_N && !expanded;
            const rankedToShow = collapsed ? ranked.slice(0, TOP_N) : ranked;

            return (
              <>
                {rankedToShow.length > 0 && (
                  <ul role="list" aria-label="Entities ranked by distinctiveness">
                    {rankedToShow.map((entity) => (
                      <EntityRankingRow
                        key={entity.entity_id}
                        entity={entity}
                        isPinned={isPinned(entity.entity_id)}
                        onTogglePin={handleTogglePin}
                      />
                    ))}
                  </ul>
                )}

                {!collapsed && alsoAppears.length > 0 && (
                  <div className="mt-6">
                    <h3
                      className={`text-sm font-semibold uppercase tracking-wide text-${colorTokens.text.tertiary} mb-2`}
                    >
                      Also appears
                    </h3>
                    <ul role="list" aria-label="Entities that appear in exactly one video">
                      {alsoAppears.map((entity) => (
                        <EntityRankingRow
                          key={entity.entity_id}
                          entity={entity}
                          isPinned={isPinned(entity.entity_id)}
                          onTogglePin={handleTogglePin}
                        />
                      ))}
                    </ul>
                  </div>
                )}

                {total > TOP_N && (
                  <button
                    type="button"
                    onClick={() => setExpanded((v) => !v)}
                    aria-expanded={expanded}
                    className="mt-4 inline-flex items-center rounded text-sm font-medium text-blue-600 hover:text-blue-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-1"
                  >
                    {expanded ? "Show less" : `Show all ${total}`}
                  </button>
                )}
              </>
            );
          })()}
        </>
      )}
    </section>
  );
}
