"""add_entity_mentions_table

Revision ID: b2e4f8a1c9d3
Revises: a7c3d9e5f1b4
Create Date: 2026-03-07 12:00:00.000000

This migration implements the entity mentions schema for Feature 038
(Entity Mention Detection). It creates the entity_mentions table that
links named entities to the transcript segments where they appear.

New Tables:
1. entity_mentions - Junction table recording every detected entity occurrence
   within a transcript segment.

Key Features:
- UUIDv7 primary key (time-ordered, generated by uuid_utils.uuid7)
- FK to named_entities(id) with ON DELETE CASCADE
- FK to transcript_segments(id) with ON DELETE CASCADE
- Denormalized video_id / language_code columns for direct lookup
- UNIQUE constraint on (entity_id, segment_id, mention_text) to prevent
  duplicate detection records for the same span
- CHECK constraint enforcing valid detection_method values
- CHECK constraint enforcing confidence in [0.0, 1.0]
- 5 performance indexes covering common query patterns
- Fully reversible downgrade

Related: Feature 038 (Entity Mention Detection), Tasks T001-T005
Architecture: ADR-003 Tag Normalization (entity extraction pipeline)
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision = "b2e4f8a1c9d3"
down_revision = "a7c3d9e5f1b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Create entity_mentions table with all constraints and indexes.

    Operations performed:
    1. Create entity_mentions table with UUID PK, FKs, columns, and constraints
    2. Create 5 performance indexes
    """
    # =========================================================================
    # TABLE: entity_mentions
    # =========================================================================
    op.create_table(
        "entity_mentions",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("entity_id", UUID(as_uuid=True), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(20), nullable=False),
        sa.Column("language_code", sa.String(10), nullable=False),
        sa.Column("mention_text", sa.String(500), nullable=False),
        sa.Column(
            "detection_method",
            sa.String(30),
            nullable=False,
            server_default=sa.text("'rule_match'"),
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=False,
            server_default=sa.text("1.0"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        # Primary key
        sa.PrimaryKeyConstraint("id", name="pk_entity_mentions"),
        # Foreign key to named_entities
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["named_entities.id"],
            name="fk_entity_mentions_entity",
            ondelete="CASCADE",
        ),
        # Foreign key to transcript_segments
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["transcript_segments.id"],
            name="fk_entity_mentions_segment",
            ondelete="CASCADE",
        ),
        # Uniqueness: one mention record per (entity, segment, text span)
        sa.UniqueConstraint(
            "entity_id",
            "segment_id",
            "mention_text",
            name="uq_entity_mention_entity_segment_text",
        ),
        # Detection method must be a recognised value
        sa.CheckConstraint(
            "detection_method IN ('rule_match', 'spacy_ner', 'llm_extraction', 'manual')",
            name="chk_entity_mention_detection_method_valid",
        ),
        # Confidence must be in [0.0, 1.0]
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name="chk_entity_mention_confidence_range",
        ),
    )

    # =========================================================================
    # INDEXES on entity_mentions
    # =========================================================================

    # Index 1: Look up all mentions for a given entity
    op.create_index(
        "ix_entity_mentions_entity_id",
        "entity_mentions",
        ["entity_id"],
        unique=False,
    )

    # Index 2: Look up all entity mentions within a segment
    op.create_index(
        "ix_entity_mentions_segment_id",
        "entity_mentions",
        ["segment_id"],
        unique=False,
    )

    # Index 3: Look up all mentions for a given video (cross-segment queries)
    op.create_index(
        "ix_entity_mentions_video_id",
        "entity_mentions",
        ["video_id"],
        unique=False,
    )

    # Index 4: Look up mentions for a video+language combination
    op.create_index(
        "ix_entity_mentions_video_language",
        "entity_mentions",
        ["video_id", "language_code"],
        unique=False,
    )

    # Index 5: Filter / aggregate by detection method
    op.create_index(
        "ix_entity_mentions_detection_method",
        "entity_mentions",
        ["detection_method"],
        unique=False,
    )


def downgrade() -> None:
    """
    Drop entity_mentions table and all associated indexes.

    WARNING: This will permanently delete all entity mention records including:
    - All entity-to-segment linkage records
    - Detection method and confidence metadata

    Ensure you have backups if this data is needed.

    Drop order reverses upgrade to respect FK constraints:
    1. Drop indexes
    2. Drop table (removes FKs to named_entities and transcript_segments)
    """
    # =========================================================================
    # DROP INDEXES (reverse order of creation)
    # =========================================================================

    op.drop_index(
        "ix_entity_mentions_detection_method",
        table_name="entity_mentions",
    )
    op.drop_index(
        "ix_entity_mentions_video_language",
        table_name="entity_mentions",
    )
    op.drop_index(
        "ix_entity_mentions_video_id",
        table_name="entity_mentions",
    )
    op.drop_index(
        "ix_entity_mentions_segment_id",
        table_name="entity_mentions",
    )
    op.drop_index(
        "ix_entity_mentions_entity_id",
        table_name="entity_mentions",
    )

    # =========================================================================
    # DROP TABLE
    # =========================================================================

    op.drop_table("entity_mentions")
