"""add entity_operation_logs table

Revision ID: d5f9a2c7b1e8
Revises: a7b9c1d3e5f7
Create Date: 2026-07-22 00:00:00.000000

Creates the ``entity_operation_logs`` audit table for named-entity curation
edits (display name / description). Each row records the before/after snapshot
and rollback data for a single edit, mirroring the ``tag_operation_logs``
pattern, and supports undo via the ``rolled_back`` flag (Feature 057, FR-016,
FR-017).

New Tables:
1. entity_operation_logs — audit + rollback log for entity name/description
   edits.

Key Features:
- UUIDv7 primary key (time-ordered, generated by uuid_utils.uuid7)
- FK to named_entities(id) with ON DELETE CASCADE
- rollback_data JSONB (before/after/changed_fields snapshot)
- CHECK constraint restricting operation_type to 'update'
- Indexes on entity_id and performed_at
- Fully reversible downgrade

Related: Feature 057 (Entity Display-Name Control), Task T015
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID

# revision identifiers, used by Alembic.
revision = "d5f9a2c7b1e8"
down_revision = "a7b9c1d3e5f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create entity_operation_logs table with constraints and indexes."""
    op.create_table(
        "entity_operation_logs",
        sa.Column("id", PGUUID(as_uuid=True), nullable=False),
        sa.Column("entity_id", PGUUID(as_uuid=True), nullable=False),
        sa.Column(
            "operation_type",
            sa.String(30),
            nullable=False,
            server_default=sa.text("'update'"),
        ),
        sa.Column(
            "rollback_data",
            JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "performed_by",
            sa.String(100),
            nullable=False,
            server_default=sa.text("'system'"),
        ),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "rolled_back",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "rolled_back_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_entity_operation_logs"),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["named_entities.id"],
            name="fk_entity_operation_logs_entity",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "operation_type IN ('update')",
            name="chk_entity_operation_type_valid",
        ),
    )

    op.create_index(
        "idx_entity_operation_logs_entity_id",
        "entity_operation_logs",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        "idx_entity_operation_logs_performed_at",
        "entity_operation_logs",
        ["performed_at"],
        unique=False,
    )


def downgrade() -> None:
    """Drop entity_operation_logs table and its indexes."""
    op.drop_index(
        "idx_entity_operation_logs_performed_at",
        table_name="entity_operation_logs",
    )
    op.drop_index(
        "idx_entity_operation_logs_entity_id",
        table_name="entity_operation_logs",
    )
    op.drop_table("entity_operation_logs")
