"""Initial database schema with all core models

Revision ID: 409d8c2c117d
Revises:
Create Date: 2025-07-14 15:34:04.656573

"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "409d8c2c117d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("channel_id", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("subscriber_count", sa.BigInteger(), nullable=True),
        sa.Column("video_count", sa.Integer(), nullable=True),
        sa.Column("default_language", sa.String(length=10), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    op.create_table(
        "topic_categories",
        sa.Column("topic_id", sa.String(length=50), nullable=False),
        sa.Column("category_name", sa.String(length=255), nullable=False),
        sa.Column("parent_topic_id", sa.String(length=50), nullable=True),
        sa.Column("topic_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_topic_id"],
            ["topic_categories.topic_id"],
        ),
        sa.PrimaryKeyConstraint("topic_id"),
    )
    op.create_table(
        "user_language_preferences",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("language_code", sa.String(length=10), nullable=False),
        sa.Column("preference_type", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("auto_download_transcripts", sa.Boolean(), nullable=False),
        sa.Column("learning_goal", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "language_code"),
    )
    op.create_table(
        "channel_keywords",
        sa.Column("channel_id", sa.String(length=24), nullable=False),
        sa.Column("keyword", sa.String(length=100), nullable=False),
        sa.Column("keyword_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.channel_id"],
        ),
        sa.PrimaryKeyConstraint("channel_id", "keyword"),
    )
    op.create_table(
        "playlists",
        sa.Column("playlist_id", sa.String(length=34), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_language", sa.String(length=10), nullable=True),
        sa.Column("privacy_status", sa.String(length=20), nullable=False),
        sa.Column("channel_id", sa.String(length=24), nullable=False),
        sa.Column("video_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.channel_id"],
        ),
        sa.PrimaryKeyConstraint("playlist_id"),
    )
    op.create_table(
        "videos",
        sa.Column("video_id", sa.String(length=20), nullable=False),
        sa.Column("channel_id", sa.String(length=24), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("upload_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("made_for_kids", sa.Boolean(), nullable=False),
        sa.Column("self_declared_made_for_kids", sa.Boolean(), nullable=False),
        sa.Column("default_language", sa.String(length=10), nullable=True),
        sa.Column("default_audio_language", sa.String(length=10), nullable=True),
        sa.Column(
            "available_languages",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "region_restriction", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "content_rating", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("view_count", sa.BigInteger(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("deleted_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.channel_id"],
        ),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_table(
        "user_videos",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("video_id", sa.String(length=20), nullable=False),
        sa.Column("watched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watch_duration", sa.Integer(), nullable=True),
        sa.Column("completion_percentage", sa.Float(), nullable=True),
        sa.Column("rewatch_count", sa.Integer(), nullable=False),
        sa.Column("liked", sa.Boolean(), nullable=False),
        sa.Column("disliked", sa.Boolean(), nullable=False),
        sa.Column("saved_to_playlist", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "video_id"),
    )
    op.create_table(
        "video_localizations",
        sa.Column("video_id", sa.String(length=20), nullable=False),
        sa.Column("language_code", sa.String(length=10), nullable=False),
        sa.Column("localized_title", sa.Text(), nullable=False),
        sa.Column("localized_description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("video_id", "language_code"),
    )
    op.create_table(
        "video_tags",
        sa.Column("video_id", sa.String(length=20), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.Column("tag_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("video_id", "tag"),
    )
    op.create_table(
        "video_transcripts",
        sa.Column("video_id", sa.String(length=20), nullable=False),
        sa.Column("language_code", sa.String(length=10), nullable=False),
        sa.Column("transcript_text", sa.Text(), nullable=False),
        sa.Column("transcript_type", sa.String(length=20), nullable=False),
        sa.Column("download_reason", sa.String(length=30), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("is_cc", sa.Boolean(), nullable=False),
        sa.Column("is_auto_synced", sa.Boolean(), nullable=False),
        sa.Column("track_kind", sa.String(length=20), nullable=False),
        sa.Column("caption_name", sa.String(length=255), nullable=True),
        sa.Column(
            "downloaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("video_id", "language_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_transcripts")
    op.drop_table("video_tags")
    op.drop_table("video_localizations")
    op.drop_table("user_videos")
    op.drop_table("videos")
    op.drop_table("playlists")
    op.drop_table("channel_keywords")
    op.drop_table("user_language_preferences")
    op.drop_table("topic_categories")
    op.drop_table("channels")
    # ### end Alembic commands ###
