"""add_playlist_published_at_and_deleted_flag

Revision ID: 481bf7ae4087
Revises: 8d541f1dd05e
Create Date: 2026-01-04 21:13:42.715298

"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "481bf7ae4087"
down_revision = "8d541f1dd05e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "playlists",
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "playlists",
        sa.Column("deleted_flag", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.alter_column(
        "video_categories",
        "category_id",
        existing_type=sa.VARCHAR(length=10),
        comment="YouTube category ID",
        existing_nullable=False,
    )
    op.alter_column(
        "video_categories",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment="Category name",
        existing_nullable=False,
    )
    op.alter_column(
        "video_categories",
        "assignable",
        existing_type=sa.BOOLEAN(),
        comment="Whether creators can select this category",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "video_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Record creation timestamp",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "videos",
        "category_id",
        existing_type=sa.VARCHAR(length=10),
        comment="YouTube video category ID",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "videos",
        "category_id",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="YouTube video category ID",
        existing_nullable=True,
    )
    op.alter_column(
        "video_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Record creation timestamp",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "video_categories",
        "assignable",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Whether creators can select this category",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "video_categories",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Category name",
        existing_nullable=False,
    )
    op.alter_column(
        "video_categories",
        "category_id",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="YouTube category ID",
        existing_nullable=False,
    )
    op.drop_column("playlists", "deleted_flag")
    op.drop_column("playlists", "published_at")
    # ### end Alembic commands ###
