"""add recovery provenance join tables (ADR-011)

Revision ID: 624d8b0b0ebe
Revises: 68516632f494
Create Date: 2026-08-10 06:03:18.244127

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "624d8b0b0ebe"
down_revision = "68516632f494"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_recovery_sources",
        sa.Column("channel_id", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_detail", sa.String(length=100), nullable=True),
        sa.Column(
            "recovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fields_written", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.channel_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("channel_id", "source"),
        comment="Append-only provenance: which sources contributed to a channel (ADR-011)",
    )
    op.create_index(
        "idx_channel_recovery_sources_source",
        "channel_recovery_sources",
        ["source"],
        unique=False,
    )
    op.create_table(
        "video_recovery_sources",
        sa.Column("video_id", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_detail", sa.String(length=100), nullable=True),
        sa.Column(
            "recovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fields_written", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(["video_id"], ["videos.video_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("video_id", "source"),
        comment="Append-only provenance: which sources contributed to a video (ADR-011)",
    )
    op.create_index(
        "idx_video_recovery_sources_source",
        "video_recovery_sources",
        ["source"],
        unique=False,
    )
    # NOTE: autogenerate also proposed creating `idx_video_topics_topic_id` and
    # `idx_videos_category_id`. Both were removed by hand. They are created by
    # 20260209_add_video_classification_filter_indexes.py and exist in
    # production; they are missing only from the local development database,
    # which was restored from a backup rather than migrated forward. That is
    # dev-environment drift, not schema drift, and bundling it here would put an
    # unrelated change in a provenance migration.

    # ── backfill ────────────────────────────────────────────────────────────
    #
    # Project the existing single-valued columns into the join table, splitting
    # the `wayback:20210101080938` convention into its two facts. Packing them
    # into one string is what destroyed the snapshot timestamps this table
    # exists to preserve, so the split happens here rather than being deferred.
    #
    # Small enough to run inline: 4,132 videos and 291 channels in production,
    # zero on a fresh database (so this is a no-op in CI).
    #
    # `fields_written` is deliberately left NULL. Which columns each historical
    # pass wrote was never recorded, and inventing it would be worse than
    # admitting we do not know — the column is documented as best-effort for
    # exactly this reason.
    #
    # `recovered_at` is copied straight across with no COALESCE fallback. Every
    # row with a `recovery_source` currently also has a `recovered_at`, so a
    # NULL here would mean an assumption has broken; the NOT NULL constraint
    # then aborts the migration rather than silently skipping the row or
    # substituting an invented timestamp.
    op.execute(
        """
        INSERT INTO video_recovery_sources
            (video_id, source, source_detail, recovered_at)
        SELECT video_id,
               split_part(recovery_source, ':', 1),
               NULLIF(split_part(recovery_source, ':', 2), ''),
               recovered_at
        FROM videos
        WHERE recovery_source IS NOT NULL
        ON CONFLICT (video_id, source) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO channel_recovery_sources
            (channel_id, source, source_detail, recovered_at)
        SELECT channel_id,
               split_part(recovery_source, ':', 1),
               NULLIF(split_part(recovery_source, ':', 2), ''),
               recovered_at
        FROM channels
        WHERE recovery_source IS NOT NULL
        ON CONFLICT (channel_id, source) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade database schema."""
    op.drop_index(
        "idx_video_recovery_sources_source", table_name="video_recovery_sources"
    )
    op.drop_table("video_recovery_sources")
    op.drop_index(
        "idx_channel_recovery_sources_source", table_name="channel_recovery_sources"
    )
    op.drop_table("channel_recovery_sources")
    # ### end Alembic commands ###
