"""sync video_transcripts column comments with the models

Revision ID: 68516632f494
Revises: a7c2e5d9f4b8
Create Date: 2026-08-08 10:12:57.501357

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "68516632f494"
down_revision = "a7c2e5d9f4b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "video_transcripts",
        "raw_transcript_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Complete raw API response with timestamps",
        existing_nullable=True,
    )
    op.alter_column(
        "video_transcripts",
        "has_timestamps",
        existing_type=sa.BOOLEAN(),
        comment="Whether raw data includes timing information",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "video_transcripts",
        "segment_count",
        existing_type=sa.INTEGER(),
        comment="Number of transcript segments",
        existing_nullable=True,
    )
    op.alter_column(
        "video_transcripts",
        "total_duration",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Total transcript duration in seconds",
        existing_nullable=True,
    )
    op.alter_column(
        "video_transcripts",
        "source",
        existing_type=sa.VARCHAR(length=50),
        comment="Source: youtube_transcript_api, youtube_data_api_v3, manual_upload, unknown",
        existing_nullable=False,
        existing_server_default=sa.text("'youtube_transcript_api'::character varying"),
    )
    op.alter_column(
        "video_transcripts",
        "has_corrections",
        existing_type=sa.BOOLEAN(),
        comment="Whether any segment has active corrections",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "video_transcripts",
        "last_corrected_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of most recent correction",
        existing_nullable=True,
    )
    op.alter_column(
        "video_transcripts",
        "correction_count",
        existing_type=sa.INTEGER(),
        comment="Count of active (non-reverted) corrections",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "video_transcripts",
        "correction_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Count of active (non-reverted) corrections",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "video_transcripts",
        "last_corrected_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of most recent correction",
        existing_nullable=True,
    )
    op.alter_column(
        "video_transcripts",
        "has_corrections",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Whether any segment has active corrections",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "video_transcripts",
        "source",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Source: youtube_transcript_api, youtube_data_api_v3, manual_upload, unknown",
        existing_nullable=False,
        existing_server_default=sa.text("'youtube_transcript_api'::character varying"),
    )
    op.alter_column(
        "video_transcripts",
        "total_duration",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Total transcript duration in seconds",
        existing_nullable=True,
    )
    op.alter_column(
        "video_transcripts",
        "segment_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Number of transcript segments",
        existing_nullable=True,
    )
    op.alter_column(
        "video_transcripts",
        "has_timestamps",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Whether raw data includes timing information",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "video_transcripts",
        "raw_transcript_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Complete raw API response with timestamps",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
