"""Add is_subscribed column to channels table

Revision ID: 7c9240e25f89
Revises: 409d8c2c117d
Create Date: 2025-07-27 09:39:02.178700

"""

from __future__ import annotations

import sqlalchemy as sa


from alembic import op

# revision identifiers, used by Alembic.
revision = "7c9240e25f89"
down_revision = "409d8c2c117d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column("channels", sa.Column("is_subscribed", sa.Boolean(), nullable=True))
    
    # Step 2: Set default value for existing records
    op.execute("UPDATE channels SET is_subscribed = false WHERE is_subscribed IS NULL")
    
    # Step 3: Make column NOT NULL
    op.alter_column("channels", "is_subscribed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "is_subscribed")
    # ### end Alembic commands ###
