"""Add video_topics and channel_topics junction tables

Revision ID: 7f6a1e878725
Revises: 7c9240e25f89
Create Date: 2025-07-27 20:54:05.110389

"""

from __future__ import annotations

import sqlalchemy as sa


from alembic import op

# revision identifiers, used by Alembic.
revision = "7f6a1e878725"
down_revision = "7c9240e25f89"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_topics",
        sa.Column("channel_id", sa.String(length=24), nullable=False),
        sa.Column("topic_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.channel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic_categories.topic_id"],
        ),
        sa.PrimaryKeyConstraint("channel_id", "topic_id"),
    )
    op.create_table(
        "video_topics",
        sa.Column("video_id", sa.String(length=20), nullable=False),
        sa.Column("topic_id", sa.String(length=50), nullable=False),
        sa.Column("relevance_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic_categories.topic_id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("video_id", "topic_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_topics")
    op.drop_table("channel_topics")
    # ### end Alembic commands ###
