"""index user_videos.video_id

The primary key is ``(user_id, video_id)``. A predicate on ``video_id`` alone
cannot use it, because the leading column is absent — so the playlist detail
page, which batch-loads the watched flag for its current page with
``WHERE video_id IN (...)``, scanned the entire table to resolve at most 100
ids. Measured on production: a Seq Scan over 52,668 rows, 123 ms, on every
page view with the default ``watched_status=all``.

Feature 060 made this worse in a way that is easy to miss. Collapsing watch
history to a single canonical identity left ``user_id`` with cardinality 1, so
the primary key's leading column now discriminates nothing whatsoever.

Deliberately NOT indexed here:

* ``watched_at`` — every one of the 52,668 rows has it set, so there is no
  selectivity to exploit. It becomes worth revisiting only once
  ``record_like()`` (a like without a watch, which stores ``watched_at=None``)
  produces null rows in volume.
* ``playlist_memberships.video_id`` and ``playlists.playlist_type`` — the
  overview aggregates read nearly every row by design to build a distinct
  video-id set, so an index would not reduce the work.

Plain ``CREATE INDEX`` rather than ``CONCURRENTLY``: the table is small, and
Alembic runs migrations inside a transaction, which ``CONCURRENTLY`` cannot
join.

Revision ID: c1f23f7560b7
Revises: 624d8b0b0ebe
Create Date: 2026-08-10 14:51:11.494333

"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "c1f23f7560b7"
down_revision = "624d8b0b0ebe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_user_videos_video_id", "user_videos", ["video_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_videos_video_id", table_name="user_videos")
    # ### end Alembic commands ###
