"""add playlists.unavailability_first_detected

Two-cycle unavailability confirmation for playlists (#149).

Videos have carried this column since the availability_status migration:
a first not-found sets the timestamp, and only a second consecutive miss
sets the status. Playlists were never given the same protection, so a
single bad enrichment run could flip ``deleted_flag`` on the whole library
— which it did, twice.

Nullable with no backfill, and NULL is the correct value for every existing
row: it means "no unconfirmed miss is pending," which is true of a playlist
that is live and equally true of one already marked deleted. A backfill
would be asserting a detection that never happened.

Note that this defends against a *transient* failure only. A persistent
auth failure across two consecutive runs still confirms, for playlists as
for videos. The upstream fix — not deriving not-found from a failed batch
— is what covers that case, and this is the second layer beneath it.

Revision ID: c310b5590648
Revises: c1f23f7560b7
Create Date: 2026-08-11 19:20:45.402736

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c310b5590648"
down_revision = "c1f23f7560b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "playlists",
        sa.Column(
            "unavailability_first_detected", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlists", "unavailability_first_detected")
    # ### end Alembic commands ###
