"""drop named_entities.channel_count (#170)

Revision ID: df31c1abd6d0
Revises: c310b5590648
Create Date: 2026-08-14 20:29:03.710721

The column was 0 for every entity because nothing ever wrote it, and nothing
ever read it either: no endpoint, no API schema and no frontend component
referenced it. (`topics.channel_count` and the settings figure of the same name
are different columns and are unaffected.)

Dropped rather than populated. Filling it would mean adding a writer to
`update_entity_counters`, a backfill, and a consistency assertion, all for a
value with no consumer. The counter beside it excludes ASR-error alias mentions
(#89), so any implementation would also have to reproduce that visible-name
filter or report a number inconsistent with the ones displayed next to it.

If an entity-to-channel count is wanted later — #171 proposes an entity list on
channel detail — it should arrive together with its writer. A column that exists
and is permanently zero is worse than an absent one: zero reads as an answer.

The downgrade restores the column with its original type and default, so the
data loss is limited to a value that was never anything but 0.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df31c1abd6d0"
down_revision = "c310b5590648"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("named_entities", "channel_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "named_entities",
        sa.Column(
            "channel_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
