"""Block commits that carry names from the local library into the repository.

Investigating this project means reading real data. The failure mode is not
reading it — it is carrying it across into something that gets committed: a
test fixture, a docstring, a commit message, an issue body. Once pushed to a
public remote a force-push does not undo it: the orphaned commit stays
retrievable by SHA and is listed in the repository's public events feed. Only
GitHub Support can purge it.

Terms come from ``.private-terms`` (gitignored), generated by
``gen_private_terms.py``.

**Only lines being added are checked**, not whole files. The repository already
contains around a thousand such occurrences in existing tests and changelogs;
a whole-file check would block every commit that touches them and would be
switched off the same day. Scanning the staged diff stops the bleeding without
demanding the backlog be cleaned first — the same trade-off secret scanners
make.

Fails **open** when the term list is missing, with a loud warning. A fresh
clone has no list, and a check that blocks every commit until someone runs a
database script does not survive contact with a bad morning.

Usage
-----
    python scripts/utilities/check_private_terms.py            # staged diff
    python scripts/utilities/check_private_terms.py --msg FILE # commit message
"""

from __future__ import annotations

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TERMS_FILE = ROOT / ".private-terms"


def build_pattern(terms: list[str]) -> re.Pattern[str]:
    """One case-insensitive, word-bounded alternation over every term.

    Word boundaries are what make short terms usable. Matched as a substring, a
    three-letter agency acronym occurs inside "especially" and "association" —
    measured at 1,010 hits across this repository, against 0 when matched as a
    word. Longest-first ordering reports the most specific term when one name
    contains another.
    """
    ordered = sorted(terms, key=len, reverse=True)
    return re.compile(
        r"\b(" + "|".join(re.escape(t) for t in ordered) + r")\b",
        re.IGNORECASE,
    )


def load_terms() -> list[str]:
    if not TERMS_FILE.exists():
        print(
            f"WARNING: {TERMS_FILE.name} not found — the private-name check did "
            "NOT run.\n"
            "         Generate it with: python scripts/utilities/gen_private_terms.py",
            file=sys.stderr,
        )
        return []
    return [
        line.strip()
        for line in TERMS_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def added_lines() -> list[tuple[str, str]]:
    """Return (path, line) for every line the staged diff adds."""
    proc = subprocess.run(
        ["git", "diff", "--cached", "--no-color", "-U0"],
        capture_output=True,
        text=True,
        check=False,
    )
    results: list[tuple[str, str]] = []
    current = "?"
    for line in proc.stdout.splitlines():
        if line.startswith("+++ b/"):
            current = line[6:]
        elif line.startswith("+") and not line.startswith("+++"):
            results.append((current, line[1:]))
    return results


def report(findings: list[tuple[str, str]]) -> int:
    if not findings:
        return 0
    print(
        "\nCommit blocked: content from the local library would enter the "
        "repository.\n",
        file=sys.stderr,
    )
    for where, term in findings:
        print(f"  {where}: {term!r}", file=sys.stderr)
    print(
        "\nUse neutral placeholder data in fixtures, docs, and commit messages.\n"
        "Real names belong in the database and your local notes, never in a\n"
        "commit — a public push cannot be fully undone.\n"
        "\nIf this is a false positive, remove the term from .private-terms or\n"
        "add it to ALLOWLIST in gen_private_terms.py — do not bypass the hook.\n",
        file=sys.stderr,
    )
    return 1


def main(argv: list[str]) -> int:
    terms = load_terms()
    if not terms:
        return 0
    pattern = build_pattern(terms)
    findings: list[tuple[str, str]] = []

    if len(argv) >= 2 and argv[0] == "--msg":
        message = pathlib.Path(argv[1]).read_text(encoding="utf-8")
        findings.extend(("commit message", m) for m in set(pattern.findall(message)))
    else:
        for path, line in added_lines():
            findings.extend((path, m) for m in set(pattern.findall(line)))

    return report(findings)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
