"""Block commits that carry names from the local library into the repository.

Investigating this project means reading real data. The failure mode is not
reading it — it is carrying it across into something that gets committed: a
test fixture, a docstring, a commit message, an issue body. Once pushed to a
public remote a force-push does not undo it: the orphaned commit stays
retrievable by SHA and is listed in the repository's public events feed. Only
GitHub Support can purge it.

Terms come from ``.private-terms`` (gitignored), generated by
``gen_private_terms.py``.

**Only lines being added are checked**, not whole files. The repository already
contains around a thousand such occurrences in existing tests and changelogs;
a whole-file check would block every commit that touches them and would be
switched off the same day. Scanning the staged diff stops the bleeding without
demanding the backlog be cleaned first — the same trade-off secret scanners
make.

Fails **open** when the term list is missing, with a loud warning. A fresh
clone has no list, and a check that blocks every commit until someone runs a
database script does not survive contact with a bad morning.

Usage
-----
    python scripts/utilities/check_private_terms.py            # staged diff
    python scripts/utilities/check_private_terms.py --msg FILE # commit message
"""

from __future__ import annotations

import pathlib
import re
import subprocess
import sys
import time
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parents[2]
TERMS_FILE = ROOT / ".private-terms"


def fold(text: str) -> str:
    """Strip diacritics so accent variants match a single term.

    The match is already case-insensitive, but it was accent-sensitive: a term
    stored with a diacritic (``café``) did not catch the same name written
    without it (``cafe``), and that exact gap once let a real name reach the
    public docs and CLI help. Folding both the term list and the scanned text
    through NFKD and dropping combining marks closes it. Folding only ever
    *adds* matches (the accented form still folds to the same key), so it cannot
    cause a miss the old behaviour would have caught.
    """
    return "".join(
        c for c in unicodedata.normalize("NFKD", text) if not unicodedata.combining(c)
    )


def build_pattern(terms: list[str]) -> re.Pattern[str]:
    """One case-insensitive, accent-folded, word-bounded alternation over terms.

    Word boundaries are what make short terms usable. Matched as a substring, a
    three-letter agency acronym occurs inside "especially" and "association" —
    measured at 1,010 hits across this repository, against 0 when matched as a
    word. Longest-first ordering reports the most specific term when one name
    contains another. Terms are folded (see :func:`fold`) so the pattern matches
    accent variants; the scanned text must be folded the same way before use.
    """
    ordered = sorted((fold(t) for t in terms), key=len, reverse=True)
    return re.compile(
        r"\b(" + "|".join(re.escape(t) for t in ordered) + r")\b",
        re.IGNORECASE,
    )


# A term list older than this no longer covers recently added entities. It is a
# warning rather than a block: coverage decays silently otherwise, but a hard
# stop on a stale file would fire on any machine without database access.
STALE_AFTER_DAYS = 14

# Image formats. The text check cannot read these, and a screenshot of the
# application shows real names visually — the one leak class this tool is blind
# to. Staging one earns a prompt to look at it.
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg"}


def load_terms() -> list[str]:
    if not TERMS_FILE.exists():
        print(
            f"WARNING: {TERMS_FILE.name} not found — the private-name check did "
            "NOT run.\n"
            "         Generate it with: python scripts/utilities/gen_private_terms.py",
            file=sys.stderr,
        )
        return []
    age_days = (time.time() - TERMS_FILE.stat().st_mtime) / 86400
    if age_days > STALE_AFTER_DAYS:
        print(
            f"WARNING: {TERMS_FILE.name} is {int(age_days)} days old. Entities "
            "added since then are NOT covered.\n"
            "         Refresh: python scripts/utilities/gen_private_terms.py",
            file=sys.stderr,
        )
    return [
        line.strip()
        for line in TERMS_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def warn_about_staged_images() -> None:
    """Flag staged images, which no text check can inspect."""
    proc = subprocess.run(
        ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
        capture_output=True,
        text=True,
        check=False,
    )
    images = [
        f
        for f in proc.stdout.split()
        if pathlib.Path(f).suffix.lower() in IMAGE_SUFFIXES
    ]
    if images:
        print(
            "\nNOTE: this commit adds image(s) that no text check can read:\n"
            + "".join(f"  {f}\n" for f in images)
            + "A screenshot of the app shows real names on screen. Open each one\n"
            "and look before pushing.\n",
            file=sys.stderr,
        )


def added_lines() -> list[tuple[str, str]]:
    """Return (path, line) for every line the staged diff adds."""
    proc = subprocess.run(
        ["git", "diff", "--cached", "--no-color", "-U0"],
        capture_output=True,
        text=True,
        check=False,
    )
    results: list[tuple[str, str]] = []
    current = "?"
    for line in proc.stdout.splitlines():
        if line.startswith("+++ b/"):
            current = line[6:]
        elif line.startswith("+") and not line.startswith("+++"):
            results.append((current, line[1:]))
    return results


def report(findings: list[tuple[str, str]]) -> int:
    if not findings:
        return 0
    print(
        "\nCommit blocked: content from the local library would enter the "
        "repository.\n",
        file=sys.stderr,
    )
    for where, term in findings:
        print(f"  {where}: {term!r}", file=sys.stderr)
    print(
        "\nUse neutral placeholder data in fixtures, docs, and commit messages.\n"
        "Real names belong in the database and your local notes, never in a\n"
        "commit — a public push cannot be fully undone.\n"
        "\nIf this is a false positive, remove the term from .private-terms or\n"
        "add it to ALLOWLIST in gen_private_terms.py — do not bypass the hook.\n",
        file=sys.stderr,
    )
    return 1


def main(argv: list[str]) -> int:
    terms = load_terms()
    if not terms:
        return 0
    pattern = build_pattern(terms)
    findings: list[tuple[str, str]] = []

    if len(argv) >= 2 and argv[0] == "--msg":
        message = pathlib.Path(argv[1]).read_text(encoding="utf-8")
        findings.extend(
            ("commit message", m) for m in set(pattern.findall(fold(message)))
        )
    elif argv and argv[0] == "--text":
        # Arbitrary text that never passes through git: issue bodies, pull
        # request descriptions, release notes, a forum post. Nothing can hook
        # those, so they need a check that can be run by hand before posting.
        #   python scripts/utilities/check_private_terms.py --text body.md
        #   pbpaste | python scripts/utilities/check_private_terms.py --text -
        raw = (
            sys.stdin.read()
            if len(argv) < 2 or argv[1] == "-"
            else pathlib.Path(argv[1]).read_text(encoding="utf-8")
        )
        findings.extend(("text", m) for m in set(pattern.findall(fold(raw))))
        if not findings:
            print("Clean — no library content found.")
    else:
        for path, line in added_lines():
            findings.extend((path, m) for m in set(pattern.findall(fold(line))))
        warn_about_staged_images()

    return report(findings)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
