"""
Test factories for chronovista models.

Provides factory_boy factories for creating test data with sensible defaults
and easy customization using keyword arguments.
"""

from __future__ import annotations

from .channel_keyword_factory import (
    ChannelKeywordAnalyticsFactory,
    ChannelKeywordBaseFactory,
    ChannelKeywordCreateFactory,
    ChannelKeywordFactory,
    ChannelKeywordSearchFiltersFactory,
    ChannelKeywordStatisticsFactory,
    ChannelKeywordTestData,
    ChannelKeywordUpdateFactory,
    create_channel_keyword,
    create_channel_keyword_analytics,
    create_channel_keyword_create,
    create_channel_keyword_filters,
    create_channel_keyword_statistics,
    create_channel_keyword_update,
)
from .channel_topic_factory import (
    ChannelTopicBaseFactory,
    ChannelTopicCreateFactory,
    ChannelTopicFactory,
    ChannelTopicSearchFiltersFactory,
    ChannelTopicStatisticsFactory,
    ChannelTopicTestData,
    ChannelTopicUpdateFactory,
    create_channel_topic,
    create_channel_topic_create,
    create_channel_topic_filters,
    create_channel_topic_statistics,
    create_channel_topic_update,
)
from .id_factory import (
    TestIds,
    YouTubeIdFactory,
    channel_id,
    playlist_id,
    topic_id,
    user_id,
    video_id,
)
from .playlist_factory import (
    PlaylistBaseFactory,
    PlaylistCreateFactory,
    PlaylistFactory,
    PlaylistSearchFiltersFactory,
    PlaylistStatisticsFactory,
    PlaylistTestData,
    PlaylistUpdateFactory,
    create_playlist,
    create_playlist_create,
    create_playlist_filters,
    create_playlist_statistics,
    create_playlist_update,
)
from .takeout_watch_entry_factory import (
    TakeoutWatchEntryFactory,
    TakeoutWatchEntryMinimalFactory,
    TakeoutWatchEntryTechFactory,
    TakeoutWatchEntryTestData,
    TakeoutWatchEntryWithTimeFactory,
    create_batch_takeout_watch_entries,
    create_minimal_takeout_watch_entry,
    create_takeout_watch_entry,
    create_takeout_watch_entry_with_time,
    create_tech_takeout_watch_entry,
)
from .topic_category_factory import (
    TopicCategoryAnalyticsFactory,
    TopicCategoryBaseFactory,
    TopicCategoryCreateFactory,
    TopicCategoryFactory,
    TopicCategoryHierarchyFactory,
    TopicCategorySearchFiltersFactory,
    TopicCategoryStatisticsFactory,
    TopicCategoryTestData,
    TopicCategoryUpdateFactory,
    create_topic_category,
    create_topic_category_analytics,
    create_topic_category_create,
    create_topic_category_filters,
    create_topic_category_hierarchy,
    create_topic_category_statistics,
    create_topic_category_update,
)
from .video_localization_factory import (
    VideoLocalizationBaseFactory,
    VideoLocalizationCreateFactory,
    VideoLocalizationFactory,
    VideoLocalizationSearchFiltersFactory,
    VideoLocalizationStatisticsFactory,
    VideoLocalizationTestData,
    VideoLocalizationUpdateFactory,
    create_video_localization,
    create_video_localization_create,
    create_video_localization_filters,
    create_video_localization_statistics,
    create_video_localization_update,
)
from .video_tag_factory import (
    VideoTagBaseFactory,
    VideoTagCreateFactory,
    VideoTagFactory,
    VideoTagSearchFiltersFactory,
    VideoTagStatisticsFactory,
    VideoTagTestData,
    VideoTagUpdateFactory,
    create_video_tag,
    create_video_tag_create,
    create_video_tag_filters,
    create_video_tag_statistics,
    create_video_tag_update,
)
from .video_topic_factory import (
    VideoTopicBaseFactory,
    VideoTopicCreateFactory,
    VideoTopicFactory,
    VideoTopicSearchFiltersFactory,
    VideoTopicStatisticsFactory,
    VideoTopicTestData,
    VideoTopicUpdateFactory,
    create_video_topic,
    create_video_topic_create,
    create_video_topic_filters,
    create_video_topic_statistics,
    create_video_topic_update,
)
from .transcript_segment_factory import (
    TranscriptSegmentBaseFactory,
    TranscriptSegmentCreateFactory,
    TranscriptSegmentFactory,
    TranscriptSegmentResponseFactory,
    TranscriptSegmentTestData,
    create_batch_transcript_segments,
    create_corrected_transcript_segment,
    create_transcript_segment,
    create_transcript_segment_base,
    create_transcript_segment_create,
    create_transcript_segment_response,
)

__all__ = [
    # VideoTag factories
    "VideoTagBaseFactory",
    "VideoTagCreateFactory",
    "VideoTagUpdateFactory",
    "VideoTagFactory",
    "VideoTagSearchFiltersFactory",
    "VideoTagStatisticsFactory",
    "create_video_tag",
    "create_video_tag_create",
    "create_video_tag_update",
    "create_video_tag_filters",
    "create_video_tag_statistics",
    "VideoTagTestData",
    # VideoTopic factories
    "VideoTopicBaseFactory",
    "VideoTopicCreateFactory",
    "VideoTopicUpdateFactory",
    "VideoTopicFactory",
    "VideoTopicSearchFiltersFactory",
    "VideoTopicStatisticsFactory",
    "create_video_topic",
    "create_video_topic_create",
    "create_video_topic_update",
    "create_video_topic_filters",
    "create_video_topic_statistics",
    "VideoTopicTestData",
    # VideoLocalization factories
    "VideoLocalizationBaseFactory",
    "VideoLocalizationCreateFactory",
    "VideoLocalizationUpdateFactory",
    "VideoLocalizationFactory",
    "VideoLocalizationSearchFiltersFactory",
    "VideoLocalizationStatisticsFactory",
    "create_video_localization",
    "create_video_localization_create",
    "create_video_localization_update",
    "create_video_localization_filters",
    "create_video_localization_statistics",
    "VideoLocalizationTestData",
    # ChannelKeyword factories
    "ChannelKeywordBaseFactory",
    "ChannelKeywordCreateFactory",
    "ChannelKeywordUpdateFactory",
    "ChannelKeywordFactory",
    "ChannelKeywordSearchFiltersFactory",
    "ChannelKeywordStatisticsFactory",
    "ChannelKeywordAnalyticsFactory",
    "create_channel_keyword",
    "create_channel_keyword_create",
    "create_channel_keyword_update",
    "create_channel_keyword_filters",
    "create_channel_keyword_statistics",
    "create_channel_keyword_analytics",
    "ChannelKeywordTestData",
    # ChannelTopic factories
    "ChannelTopicBaseFactory",
    "ChannelTopicCreateFactory",
    "ChannelTopicUpdateFactory",
    "ChannelTopicFactory",
    "ChannelTopicSearchFiltersFactory",
    "ChannelTopicStatisticsFactory",
    "create_channel_topic",
    "create_channel_topic_create",
    "create_channel_topic_update",
    "create_channel_topic_filters",
    "create_channel_topic_statistics",
    "ChannelTopicTestData",
    # TopicCategory factories
    "TopicCategoryBaseFactory",
    "TopicCategoryCreateFactory",
    "TopicCategoryUpdateFactory",
    "TopicCategoryFactory",
    "TopicCategorySearchFiltersFactory",
    "TopicCategoryStatisticsFactory",
    "TopicCategoryHierarchyFactory",
    "TopicCategoryAnalyticsFactory",
    "create_topic_category",
    "create_topic_category_create",
    "create_topic_category_update",
    "create_topic_category_filters",
    "create_topic_category_statistics",
    "create_topic_category_hierarchy",
    "create_topic_category_analytics",
    "TopicCategoryTestData",
    # Playlist factories
    "PlaylistBaseFactory",
    "PlaylistCreateFactory",
    "PlaylistUpdateFactory",
    "PlaylistFactory",
    "PlaylistSearchFiltersFactory",
    "PlaylistStatisticsFactory",
    "create_playlist",
    "create_playlist_create",
    "create_playlist_update",
    "create_playlist_filters",
    "create_playlist_statistics",
    "PlaylistTestData",
    # ID factories
    "YouTubeIdFactory",
    "TestIds",
    "channel_id",
    "video_id",
    "playlist_id",
    "user_id",
    "topic_id",
    # TakeoutWatchEntry factories
    "TakeoutWatchEntryFactory",
    "TakeoutWatchEntryMinimalFactory",
    "TakeoutWatchEntryWithTimeFactory",
    "TakeoutWatchEntryTechFactory",
    "TakeoutWatchEntryTestData",
    "create_takeout_watch_entry",
    "create_minimal_takeout_watch_entry",
    "create_takeout_watch_entry_with_time",
    "create_tech_takeout_watch_entry",
    "create_batch_takeout_watch_entries",
    # TranscriptSegment factories
    "TranscriptSegmentBaseFactory",
    "TranscriptSegmentCreateFactory",
    "TranscriptSegmentFactory",
    "TranscriptSegmentResponseFactory",
    "TranscriptSegmentTestData",
    "create_transcript_segment",
    "create_transcript_segment_base",
    "create_transcript_segment_create",
    "create_transcript_segment_response",
    "create_batch_transcript_segments",
    "create_corrected_transcript_segment",
]
